base:
  config:
    oauth:
      hostname: localhost
      port: 9001
spring:
  application:
    name: spt-provider-user
  datasource:
    druid:
      url: jdbc:mysql://192.168.223.128:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456-abc
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 10.67.78.82:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

server:
  port: 9502

mybatis:
    type-aliases-package: com.msunsoft.spt.business.domain.user
    mapper-locations: classpath:mapper/user/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.msunsoft.spt.business.mapper.user: debug

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

